package com.example.WayPass.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;

@DynamoDBTable(tableName = "accounts")
public class Account {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String accountId;

    @DynamoDBAttribute
    private String serviceName;

    @DynamoDBAttribute
    private String accountName;

    @DynamoDBAttribute
    private String hashedPassword;

    public Account() {}

    public Account(String accountId, String serviceName, String accountName, String hashedPassword){
        this.accountId = accountId;
        this.serviceName = serviceName;
        this.accountName = accountName;
        this.hashedPassword = hashedPassword;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getServiceName(){
        return serviceName;
    }

    public void setServiceName(String serviceName){
        this.serviceName = serviceName;
    }

    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Account account = (Account) o;
        return Objects.equals(getAccountId(), account.getAccountId()) && Objects.equals(getServiceName(), account.getServiceName()) && Objects.equals(getAccountName(), account.getAccountName()) && Objects.equals(getHashedPassword(), account.getHashedPassword());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAccountId(), getServiceName(), getAccountName(), getHashedPassword());
    }

    @Override
    public String toString() {
        return "Account{" +
                "accountId='" + accountId + '\'' +
                ", serviceName='" + serviceName + '\'' +
                ", accountName='" + accountName + '\'' +
                ", hashedPassword='" + hashedPassword + '\'' +
                '}';
    }
}
